#!/usr/bin/env python3
"""Step 3: the eyes for the reveal in the dark.  python3 tools/cat/03_eyes.py

  -> assets/cat/eyes.json      centre / radius / ellipse of each eye, in cutout (padded canvas) pixels
  -> assets/cat/cat-eyes.png   RGBA on the cutout canvas: only the two eyes (iris, pupil, lid line), soft-matted,
                               slightly richer in colour than the photo so they read from the back of a hall
  -> work/check_eyes.png
"""
import json
import os

import cv2
import numpy as np

from catlib import ASSETS, CAN_H, CAN_W, PAD_TOP, WORK, on_colour, pad_canvas, save_rgba, smoothstep

bgr = cv2.imread(os.path.join(WORK, 'src_clean.png')).astype(np.float32)
H, W = bgr.shape[:2]
lum = cv2.cvtColor(bgr.astype(np.uint8), cv2.COLOR_BGR2GRAY).astype(np.float32)

# hand-fitted ellipses of the eye openings (photo pixels; angle = major axis, degrees, image convention y down)
EYES = [
    {'id': 'amber', 'side': 'far (cat\'s right eye)', 'cx': 441, 'cy': 462, 'rx': 61, 'ry': 36, 'angle': -52.5, 'sat': 1.75, 'gain': 1.35, 'tint': (0.86, 1.0, 1.10)},
    {'id': 'blue', 'side': 'near (cat\'s left eye)', 'cx': 648, 'cy': 579, 'rx': 67, 'ry': 63, 'angle': 0.0, 'sat': 1.9, 'gain': 1.22, 'tint': (1.12, 1.0, 0.90)},
]

yy, xx = np.mgrid[0:H, 0:W].astype(np.float32)
matte = np.zeros((H, W), np.float32)
col = bgr.copy()
out = []
for e in EYES:
    th = np.deg2rad(e['angle'])
    dx, dy = xx - e['cx'], yy - e['cy']
    u = (dx * np.cos(th) + dy * np.sin(th)) / e['rx']
    v = (-dx * np.sin(th) + dy * np.cos(th)) / e['ry']
    rho = np.sqrt(u * u + v * v)
    ell = 1 - smoothstep(0.80, 1.03, rho)                     # the opening, feathered
    dark = cv2.GaussianBlur(smoothstep(222, 168, lum), (0, 0), 1.6)   # iris / pupil / lid line vs white fur
    core = 1 - smoothstep(0.55, 0.80, rho)                    # reflections inside the eye stay in
    m = ell * np.maximum(dark, core)
    m = cv2.GaussianBlur(m, (0, 0), 1.2)
    matte = np.maximum(matte, m)
    # richer colour inside this eye only
    sel = (rho < 1.3)
    hsv = cv2.cvtColor(np.clip(bgr / 255, 0, 1), cv2.COLOR_BGR2HSV)
    hsv[..., 1] = np.clip(hsv[..., 1] * e['sat'], 0, 1)
    hsv[..., 2] = np.clip(hsv[..., 2] * e['gain'], 0, 1)
    rich = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR) * 255 * np.array(e['tint'], np.float32)
    col = np.where(sel[..., None], rich, col)
    area = float((m > 0.5).sum())
    out.append({
        'id': e['id'], 'side': e['side'],
        'cx': e['cx'], 'cy': e['cy'] + PAD_TOP,
        'r': round(float(np.sqrt(e['rx'] * e['ry'])), 1),
        'rx': e['rx'], 'ry': e['ry'], 'angle': e['angle'],
        'matte_area_px': round(area),
    })

save_rgba(os.path.join(ASSETS, 'cat-eyes.png'), pad_canvas(np.clip(col, 0, 255)), pad_canvas(matte))
meta = {
    '_note': 'Pixel coordinates on the cutout canvas shared by cat-cutout.png / cat-party.png / cat-eyes.png '
             '(photo is 1080x1776, padded with pad_top transparent rows above it). r = sqrt(rx*ry); angle is the '
             'major-axis rotation in degrees (y down). Generated by tools/cat/03_eyes.py.',
    'canvas': {'w': CAN_W, 'h': CAN_H, 'pad_top': PAD_TOP},
    'eyes': out,
}
with open(os.path.join(ASSETS, 'eyes.json'), 'w') as f:
    json.dump(meta, f, indent=2)

chk = on_colour(np.clip(col, 0, 255), matte, (0, 0, 0))[380:700, 340:760]
cv2.imwrite(os.path.join(WORK, 'check_eyes.png'), cv2.resize(chk, None, fx=2, fy=2, interpolation=cv2.INTER_CUBIC))
print(json.dumps(out, indent=1))
